### ISSUE TITLE
I18N.php Fehler

### ISSUE THREAD

**Issue by Kevin199224** [delight-im/OpenSoccer#241]
Hello, i hope German is okay, but my English is not good.

Wenn ich meine Seite www.soccer-chef.cwsurf.de aufrufe, erscheint folgender Fehler:
Fatal error: Call to undefined function locale_accept_from_http() in /home/www/cwcity/hosting/s/o/soccer-chef/htdocs/classes/I18N.php on line 97

Wie kann ich den Fehler beheben?

**Comment by cosme12** [comment]
Comment that line with //

**Comment by mwaclawek** [comment]
@cosme12 Thanks a lot for helping out!

@Kevin199224 You have to install the `intl` extension. Read more [here](https://github.com/delight-im/OpenSoccer#setup) and in this [other issue](https://github.com/delight-im/OpenSoccer/issues/240) covering the same problem.

Commenting out, as @cosme12 explained, does also work. But you won't have automatic language detection then.
