### ISSUE TITLE
I want to use the Match Engine Code for my Game

### ISSUE THREAD

**Issue by tusharagg87** [delight-im/OpenSoccer#242]
I am trying to make a game like Football Manager but I am not a coder like you.

I wanted to know whether I can use your code for the match simulation part for my game. My idea of the game is pretty different from yours but the match engines are pretty much same everywhere.

Will be looking forward to your reply.

I apologize if this is not the right place to ask these sort of question. 

Have a nice day.

**Comment by mwaclawek** [comment]
Thanks for your question!

You'll definitely need to acquire some coding skills to do this. But in general, you can use *any* part of this game *as long as* you comply with the license terms:
https://github.com/delight-im/OpenSoccer#license

You can read about what is "Required", "Permitted" and "Forbidden" with this license here:
http://choosealicense.com/licenses/gpl-3.0/

Diving into that code and understanding it (at least so well that you can re-use it) may take some time, of course.

The code is located here:
https://github.com/delight-im/OpenSoccer/blob/master/Website/aa_spieltag_simulation.php

Good luck!
