### ISSUE TITLE
Mobile css

### ISSUE THREAD

**Issue by cosme12** [delight-im/OpenSoccer#252]
The new mobile css looks good but it broke the desktop layout. Now field background got "zoomed" and half of it is missing and pixelated. ```background-size: cover; background-position: center bottom;``` is causing it.

**Comment by mwaclawek** [comment]
Thanks!

Changing the height of `.os-lineup-field` from `480px` to `400px` in the CSS should help. Can you try this?

If we make this change, however, we'll have to add `height: 480px;` for `.os-lineup-field` in the media query at the end of the CSS file.

**Comment by cosme12** [comment]
Changing to 400px seems to work. Not sure what do you mean in the 2nd part.
Also, have you tought about adding a background to the ```body { }``` insteed of the gray we have already?

**Comment by mwaclawek** [comment]
Has been fixed in https://github.com/delight-im/OpenSoccer/commit/c05c028b6f6f405b2233c91506b20252de2de288

Let's talk about the `body` background in a separate issue :)
