### ISSUE TITLE
Android app layout bug

### ISSUE THREAD

**Issue by cosme12** [delight-im/OpenSoccer#254]
Top layout is missing. No logo, everything is white.
![screenshot_2015-05-06-00-31-37](https://cloud.githubusercontent.com/assets/6611118/7487120/6f4f0fe4-f387-11e4-81fd-7bff4af1a5e3.png)

**Comment by mwaclawek** [comment]
Thank you! The reason was that Android (before version 5.0) uses outdated browser engines for the internal system browser. For those old browsers, some CSS had to be corrected.

Has been fixed in https://github.com/delight-im/OpenSoccer/commit/98aaac1a4c1e423507164d8fffc5a0429a6312d9
