### ISSUE TITLE
transfermarkt.php select tags size

### ISSUE THREAD

**Issue by cosme12** [delight-im/OpenSoccer#273]
This is how it looks now with translations:
![old](https://cloud.githubusercontent.com/assets/6611118/7552600/61ceeba4-f694-11e4-895c-cc818ef98be1.png)

This is how it looks after you replace the fixed ```width``` with ```width:auto;```
![new](https://cloud.githubusercontent.com/assets/6611118/7552603/837b3e92-f694-11e4-9d7e-35277202171d.png)

What do we do?

**Comment by mwaclawek** [comment]
Thank you!

Either that, or we replace the sizes of the first select fields per row from `width:75px` to `width:95px` and those of the second select fields from `width:120px` to `width:160px`.

I think increasing the sizes gives a more consistent result. What do you think?
