### ISSUE TITLE
Home stadium image

### ISSUE THREAD

**Issue by cosme12** [delight-im/OpenSoccer#274]
What do you think about adding home stadium image to each match?
![stadium](https://cloud.githubusercontent.com/assets/6611118/7552614/0bb02bc4-f695-11e4-9554-b528180a78ac.png)

**Comment by mwaclawek** [comment]
Oh yes, what a good idea :) Why haven't we thought about this before :) So yes, let's do it :)

We can just display it as we do on the stadium page, except that we have to find the home team's stadium data first. Right?
