### ISSUE TITLE
Translation phrases

### ISSUE THREAD

**Issue by cosme12** [delight-im/OpenSoccer#281]
Im not  sure I should make an issue for this, but I have been translating to Spanish (86% right now) and I'm having troubles with some sentences. Would you mind if I paste some so you can translate me this to Englsih? For example:

```
**index.php**
Solltest Du aber gemeinsam mit Anderen einen Rechner benutzen, unterliegt dieses Vorgehen einer Auflage, welche das Fairplay gewährleisten und schützen soll:
Unter allen diesen Accounts sind jegliche Aktivitäten, die einem der Accounts einen Vorteil verschaffen können, untersagt. Ansonsten genießen diese Accounts selbstverständlich die gleichen Rechte, Pflichten und Spielfunktionen wie die Einzelspieler.
```
I tried thousand of translators + using my imagination, but Im not even close to what does it mean. Thanks.

**Comment by mwaclawek** [comment]
Sorry for the missing English translation!

It's roughly:

```
Should you be using a single device together with others, however, there are some rules to guarantee fair play:
Among all those accounts, all activities that could give an advantage to one of them are forbidden. Otherwise, those accounts have the same rights, duties and game features as those playing alone, of course.
```

I hope there aren't too many other strings that cause problems!

**Comment by cosme12** [comment]
Thanks, here is another one. It is in the support page ```schnelle``` next to the "like" counter.

**Comment by mwaclawek** [comment]
That would be something like `fast` or `quick`. It just means how many replies the user gave within a very short period of time.
