### ISSUE TITLE
Rotating Android device

### ISSUE THREAD

**Issue by cosme12** [delight-im/OpenSoccer#285]
Rotating my phone restart the main activity redirecting me back to ```index.php```. Was it done on purpose? What would happen if we "deny" it?

**Comment by mwaclawek** [comment]
No, it wasn't done on purpose. Thanks for reporting :)

We could lock the screen orientation so that, when you rotate the device, the screen remains as if nothing changed.

Is this what you're referring to?

**Comment by cosme12** [comment]
Yes, but not locking the screen. Just being able to change the orientation without being redirected.

**Comment by mwaclawek** [comment]
Please try this:
https://github.com/delight-im/OpenSoccer/tree/master/Android/APKs

Does it work as expected now?

**Comment by cosme12** [comment]
Perfect. Good job. Also the new icon looks pretty cool. Now, is there any way we can translate the interface dinamicaly or do we need a different apk for each language?

**Comment by mwaclawek** [comment]
Thanks :)

We'll have to translate it here and I'll integrate the translations into a new APK release later:
https://www.localize.im/v/jF

Sorry for the separate process!
