### ISSUE TITLE
need help. Cant install. 

### ISSUE THREAD

**Issue by AlphabetoPT** [delight-im/OpenSoccer#297]
Hello sir.
I was testing it on WAMP server at my localhost machine and i cant run it.
Please help if you can.
Thanks.

"Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80"

**Comment by cosme12** [comment]
You should look for the error in the file error_log. Did you try doing that?

**Comment by mwaclawek** [comment]
Thanks for your question, @AlphabetoPT, and thanks for helping, @cosme12!

You should reallly try the advice that @cosme12 gave: Without more information, we cannot tell what's the problem here. The error logs will probably tell you more.

In general, this might be caused by the `.htaccess` file in the root directory of the site (in the `Website` folder). Can you try removing that file and see if it works then?

**Comment by AlphabetoPT** [comment]
is there a way that i create an ftp and sql user and u set it up under a subdomain i give u access to?
thanks

**Comment by mwaclawek** [comment]
@AlphabetoPT Sure, we can do this. Sorry for the late reply!

Please just write an email to the address that you find on our website:
http://www.opensoccer.org/impressum.php

Thank you!

**Comment by AlphabetoPT** [comment]
can we be on Teamspeak3 server while you do it?
i would like to trade some ideas.
ts.zionportugal.com
same nick.

**Comment by AlphabetoPT** [comment]
i'm still awaiting to your response to my email

**Comment by mwaclawek** [comment]
We have (and had) replied to your emails already, *twice* actually, but didn't receive any further response in return.

Please check your inbox!

**Comment by AlphabetoPT** [comment]
Sorry i had some personal situations.
May i ask to re-start the support?

**Comment by mwaclawek** [comment]
No problem!

Just send an email again or reply to the previous emails :)
