### ISSUE TITLE
Urgent Consult

### ISSUE THREAD

**Issue by joseliko7** [delight-im/OpenSoccer#298]
How do I add a background image on the web?

How do I enter the control panel?

How do I remove demo accounts?

**Comment by cosme12** [comment]
Check website/images/Refresh.php to change background.

If you are admin you can access control panel in your left menu.

Im not sure you can remove. You can probably change his password to make it unable to use.

**Comment by joseliko7** [comment]
I just installed the script on my site, but I do not know which is the key of the user's default administrator.

**Comment by cosme12** [comment]
User: Admin
Pass: admin

**Comment by joseliko7** [comment]
ok thanks!

**Comment by joseliko7** [comment]
How do I manage the computers?

**Comment by cosme12** [comment]
Once you set all the cronjobs the script manage them.

**Comment by joseliko7** [comment]
How do I configure the cronojobs?

**Comment by cosme12** [comment]
Im not sure if your server is local or not, but in your cpanel, it says "cronjobs" (there is a clock). This allow you to select some scripts you want to auto execute at certain times of the day.

**Comment by joseliko7** [comment]
I have hired a hosting and use plesk panel.

**Comment by cosme12** [comment]
I have never used it, but there is an option that says "scheduled tasks". Check it.

**Comment by mwaclawek** [comment]
Thanks for your questions, @joseliko7, and thanks for your help, @cosme12!

The documentation has been updated with regard to this issue: https://github.com/delight-im/OpenSoccer/blob/e4aa82be69685fd15625f89d3b623ba3a24ab6d6/CUSTOMIZATION.md
