### ISSUE TITLE
no diferent after games Manager Points

### ISSUE THREAD

**Issue by Europekicker** [delight-im/OpenSoccer#304]
How long for update Manager Points in the game.

We Play allready 3 times and no points 4 Manager still on 1200 Points.

?

**Comment by mwaclawek** [comment]
Are you referring to the points called `RKP` which are displayed in `/top_manager.php`, for example?

It seems you didn't set up the cron jobs correctly, then.

Please take a look at `Website/aa_buchungenBuffer.php` which gets the necessary updates from the database and applies them to the users (`elo = ...`).

**Comment by Europekicker** [comment]
/usr/bin/lynx --dump http://www.europekicker.de/aa_buchungenBuffer.php >/dev/null 

works

**Comment by Europekicker** [comment]
ok now it works....

i change the mysql user of database right to all, now works.

**Comment by mwaclawek** [comment]
Thanks for reporting the solution!

Just to clarify, executing the command `/usr/bin/lynx --dump ... > /dev/null ` alone is not enough -- you have to add this as a repeated task (i.e. as a cron job).

**Comment by Europekicker** [comment]
yes i know its a cronjob

every 10 min on 10-11 14-15 18-19 22-23   i run on own root server.

![cron](https://cloud.githubusercontent.com/assets/14942144/10773111/db615100-7cf9-11e5-8afb-6dfecff8cb89.png)

**Comment by mwaclawek** [comment]
Yes, that looks good!
