### ISSUE TITLE
Stadion expansion prices

### ISSUE THREAD

**Issue by Europekicker** [delight-im/OpenSoccer#309]
Kosten für Erweiterung: 11.880.000 + 1.200 € / Platz

Costs for extension : 11,880,000 + 1,200 € / square

how many money to use for 1000 Places more?

11.880.000.000 ?

Can you tell me how it is ?

**Comment by cosme12** [comment]
11,800,000 is a base. Buying 1 or 100 platz cost always 11,800,000 + 1,200 per each platz.

**Comment by Europekicker** [comment]
ok

**Comment by japetos** [comment]
Hello,

so formule should be: 11.880.000 € + (1.200 € x quantity of Platz)

**Comment by mwaclawek** [comment]
Exactly :) As can be seen here: https://github.com/delight-im/OpenSoccer/blob/e4aa82be69685fd15625f89d3b623ba3a24ab6d6/Website/ver_stadion.php#L49
