### ISSUE TITLE
install date and admin account

### ISSUE THREAD

**Issue by Europekicker** [delight-im/OpenSoccer#310]
I've noticed the admin account of an earlier date as my installations date, this may lead to missing the ranking calculation etc

admin :Involved since	13.07.2008 18:58

install date :2015-09-14

**Comment by mwaclawek** [comment]
You're right. This is some kind of an Easter egg ;)

The registration (and initial "last login" date) of the three default users is set to the date of the project's very beginning.

You can easily change it by modifying the column `regdate` (and `last_login`) of table `man_users`. Feel free to change it, but it really doesn't have any negative side effects.
