### ISSUE TITLE
Conjob Table man_cronjobs

### ISSUE THREAD

**Issue by Europekicker** [delight-im/OpenSoccer#316]
Last allways 0

![cronjob](https://cloud.githubusercontent.com/assets/14942144/12535666/d80b2e78-c28a-11e5-8a4c-7ed251eced1f.png)

**Comment by mwaclawek** [comment]
Thanks!

This is indeed old (unused) code as well. It's only referenced at the end of `zz3.php` in a block that is commented out:

https://github.com/delight-im/OpenSoccer/blob/e4aa82be69685fd15625f89d3b623ba3a24ab6d6/Website/zz3.php#L16

If you remove that snippet, you can also remove the database table.

**Comment by Europekicker** [comment]
ok thx
