### ISSUE TITLE
Random events

### ISSUE THREAD

**Issue by japetos** [delight-im/OpenSoccer#317]
Hi,

programmed random events. See attached files...

[aa_randomevents.txt](https://github.com/delight-im/OpenSoccer/files/102915/aa_randomevents.txt)
[man_randomevent.txt](https://github.com/delight-im/OpenSoccer/files/102916/man_randomevent.txt)

Files need to be renamed

**Comment by cosme12** [comment]
Give us some more details. What does it exactly do?

**Comment by mwaclawek** [comment]
Thanks for sharing this!

Your new feature definitely looks interesting. But please understand that we don't accept any new features here in this repository. Feel free to add this to your own game or to share it in a forked version of this repository, however :)

**Comment by japetos** [comment]
Hello,
will try to make an own fork. Random events create random events regading players (freshness, stamina, whatever) or team, such as your team recoded a music album with a C-Star and failed and just cost a bunch of money. silly stuff to bring more life into game.
