### ISSUE TITLE
Got some failures after new Installation

### ISSUE THREAD

**Issue by bornhaeusser** [delight-im/OpenSoccer#322]
![image](https://cloud.githubusercontent.com/assets/6609040/17699393/bb8484fc-63c0-11e6-8b22-5242a81ea155.png)

Some are missing.....
and also some "Umlaute" ö ä ü issues

**Comment by mwaclawek** [comment]
Thanks!

There might have been a problem with your database import.

Please note that this repository is not actively maintained anymore.
