### ISSUE TITLE
After Installation Date wrong for Personal

### ISSUE THREAD

**Issue by bornhaeusser** [delight-im/OpenSoccer#324]
Du kannst jeden Assistenten nur alle 22 Tage austauschen. Du musst also noch bis 23.01.1970 01:00 warten.

How could i fix this?

**Comment by mwaclawek** [comment]
Thanks!

A search over the code will tell you that this message is generated in line 177, 221 or 265 of `ver_personal.php`. So you should go to these lines and debug the surrounding lines of code. Some condition is not met.

Please note that this repository is not actively maintained anymore.

**Comment by bornhaeusser** [comment]
We found that the SQL Table is empty where the script Update the Table/Row

`$ch1 = "UPDATE ".$prefix."personal_changes SET zeit = ".time()." WHERE team = '".$cookie_team."' AND personal = 'Jugendtrainer' AND zeit < ".$timeout;`

Where or wen is the table filled?

**Comment by bornhaeusser** [comment]
Did insert in Database:

[Failed_insert.txt](https://github.com/delight-im/OpenSoccer/files/442393/Failed_insert.txt)

Problem solved
