### ISSUE TITLE
FILL_COM_TEAMS.txt Failure on Line 8

### ISSUE THREAD

**Issue by bornhaeusser** [delight-im/OpenSoccer#326]
Notice: Undefined variable: zeit in /FILL_COM_TEAMS.php on line 8

`$vertrag = $zeit+3600*24*7;`

**Comment by mwaclawek** [comment]
Thanks!

`$zeit` must be replaced with `time()`.

Please note that this repository is not actively maintained anymore.

**Comment by bornhaeusser** [comment]
Thanks
