### ISSUE TITLE
pokal.php on line 176 Notice: Undefined index: in

### ISSUE THREAD

**Issue by bornhaeusser** [delight-im/OpenSoccer#327]
In the Nat.Cup Page i get an Error:

pokal.php on line 176 Notice: Undefined index: in

Also some Fields in the Table are empty

<img width="611" alt="bildschirmfoto 2016-08-21 um 09 44 24" src="https://cloud.githubusercontent.com/assets/6609040/17835993/f2b18346-6783-11e6-9a45-e2ab9a5fab0e.png">

**Comment by mwaclawek** [comment]
Thanks!

You should go to line 176 in `pokal.php` and check the values that are used as keys with `var_dump`. Some of them are obviously empty. This is also the reason why the fields in the table are empty.

Please note that this repository is not actively maintained anymore.

**Comment by bornhaeusser** [comment]
It is missing a Team in the DB

![image](https://cloud.githubusercontent.com/assets/6609040/17881401/55655896-6905-11e6-8d79-2ccdc36f624e.png)
