### ISSUE TITLE
Aktion in Transfermarkt missing?

### ISSUE THREAD

**Issue by bornhaeusser** [delight-im/OpenSoccer#329]
![image](https://cloud.githubusercontent.com/assets/6609040/17883388/81792626-6912-11e6-9be8-787b42a61085.png)

Is there Missing a buttom?

**Comment by mwaclawek** [comment]
Are these your own players perhaps?

**Comment by bornhaeusser** [comment]
Found the Problem - Multiple IPs. Tested from the same ip....
(A Message would be great Multipe IP or Multiaccount.... The User does not know why there is no Aktion.
