### ISSUE TITLE
Error, i can't solve it

### ISSUE THREAD

**Issue by notawiseguy** [delight-im/OpenSoccer#333]
Hello guys, i just download this amazing source project, and its giving me this error (http://imgur.com/a/OM8DN) , and i can't solve it, what am i doing wrong? Can someone help me solve it please?
Thanks

**Comment by cosme12** [comment]
This error is because your php version is new. Some functions are not used anymore so I doesnt work. All you have to do is use and older php version and everything should work.

**Comment by notawiseguy** [comment]
Do you know which version of php should i get ? Thanks a lot

**Comment by cosme12** [comment]
I Don't remember, try 4 or 5.

**Comment by ocram** [comment]
Thanks, @cosme12!

@notawiseguy The first notice is just a warning about a deprecated feature. You can turn it off somewhere. The second notice tells you that the [Intl extension](http://php.net/manual/de/book.intl.php) is missing on your machine.

Regarding the `mysql` extension, which is still available in PHP 5.6 but is removed in PHP 7.0, there's a better solution than sticking with an old PHP version, luckily: When using PHP 7.0+, just include [this library](https://github.com/dshafik/php7-mysql-shim) which adds replacements for all the old functions whose names start with `mysql_`.
